name: Push Tests

on:
  push:
    branches:
      - '**'

jobs:
  call-pr-tests:
    uses: ./.github/workflows/pr-tests.yml

  build-publish:
    needs: call-pr-tests
    uses: ./.github/workflows/build-publish.yml
    with:
      publish: ${{ github.ref == 'refs/heads/master' }}
    secrets: inherit
